version: '2'

services:
  postgres:
    image: 'postgres:9.5'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis:
    image: 'redis:3.2-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'

  jobs:
    depends_on:
      - 'postgres'
      - 'redis'
      - 'app'
    build: .
    command: bash start_jobs
    volumes:
      - '.:/petshop_admin'
    volumes_from:
      - box


  app:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    command: bash start.sh
    ports:
      - '3000:3000'
    volumes:
      - '.:/petshop_admin'
    volumes_from:
      - box

  box:
    image: busybox
    volumes:
      - /box

  mailcatcher:
    image: tophfr/mailcatcher
    ports:
      - 1025:25
      - 1080:80

volumes:
  redis:
  postgres:
  box:
